use std::str::FromStr;

use global_hotkey::hotkey::Modifiers;
use strum_macros::{Display, EnumString};

#[napi(string_enum)]
#[derive(Debug, Display, EnumString)]
pub enum KeyCode {
  Backquote,
  Backslash,
  BracketLeft,
  BracketRight,
  Comma,
  Digit0,
  Digit1,
  Digit2,
  Digit3,
  Digit4,
  Digit5,
  Digit6,
  Digit7,
  Digit8,
  Digit9,
  Equal,
  IntlBackslash,
  IntlRo,
  IntlYen,
  KeyA,
  KeyB,
  KeyC,
  KeyD,
  KeyE,
  KeyF,
  KeyG,
  KeyH,
  KeyI,
  KeyJ,
  KeyK,
  KeyL,
  KeyM,
  KeyN,
  KeyO,
  KeyP,
  KeyQ,
  KeyR,
  KeyS,
  KeyT,
  KeyU,
  KeyV,
  KeyW,
  KeyX,
  KeyY,
  KeyZ,
  Minus,
  Period,
  Quote,
  Semicolon,
  Slash,
  AltLeft,
  AltRight,
  Backspace,
  CapsLock,
  ContextMenu,
  ControlLeft,
  ControlRight,
  Enter,
  MetaLeft,
  MetaRight,
  ShiftLeft,
  ShiftRight,
  Space,
  Tab,
  Convert,
  KanaMode,
  Lang1,
  Lang2,
  Lang3,
  Lang4,
  Lang5,
  NonConvert,
  Delete,
  End,
  Help,
  Home,
  Insert,
  PageDown,
  PageUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  NumLock,
  Numpad0,
  Numpad1,
  Numpad2,
  Numpad3,
  Numpad4,
  Numpad5,
  Numpad6,
  Numpad7,
  Numpad8,
  Numpad9,
  NumpadAdd,
  NumpadBackspace,
  NumpadClear,
  NumpadClearEntry,
  NumpadComma,
  NumpadDecimal,
  NumpadDivide,
  NumpadEnter,
  NumpadEqual,
  NumpadHash,
  NumpadMemoryAdd,
  NumpadMemoryClear,
  NumpadMemoryRecall,
  NumpadMemoryStore,
  NumpadMemorySubtract,
  NumpadMultiply,
  NumpadParenLeft,
  NumpadParenRight,
  NumpadStar,
  NumpadSubtract,
  Escape,
  Fn,
  FnLock,
  PrintScreen,
  ScrollLock,
  Pause,
  BrowserBack,
  BrowserFavorites,
  BrowserForward,
  BrowserHome,
  BrowserRefresh,
  BrowserSearch,
  BrowserStop,
  Eject,
  LaunchApp1,
  LaunchApp2,
  LaunchMail,
  MediaPlayPause,
  MediaSelect,
  MediaStop,
  MediaTrackNext,
  MediaTrackPrevious,
  Power,
  Sleep,
  AudioVolumeDown,
  AudioVolumeMute,
  AudioVolumeUp,
  WakeUp,
  Hyper,
  Super,
  Turbo,
  Abort,
  Resume,
  Suspend,
  Again,
  Copy,
  Cut,
  Find,
  Open,
  Paste,
  Props,
  Select,
  Undo,
  Hiragana,
  Katakana,
  Unidentified,
  F1,
  F2,
  F3,
  F4,
  F5,
  F6,
  F7,
  F8,
  F9,
  F10,
  F11,
  F12,
  F13,
  F14,
  F15,
  F16,
  F17,
  F18,
  F19,
  F20,
  F21,
  F22,
  F23,
  F24,
  F25,
  F26,
  F27,
  F28,
  F29,
  F30,
  F31,
  F32,
  F33,
  F34,
  F35,
  BrightnessDown,
  BrightnessUp,
  DisplayToggleIntExt,
  KeyboardLayoutSelect,
  LaunchAssistant,
  LaunchControlPanel,
  LaunchScreenSaver,
  MailForward,
  MailReply,
  MailSend,
  MediaFastForward,
  MediaPause,
  MediaPlay,
  MediaRecord,
  MediaRewind,
  MicrophoneMuteToggle,
  PrivacyScreenToggle,
  SelectTask,
  ShowAllWindows,
  ZoomToggle,
}

impl KeyCode {
  pub fn global_hotkeys(&self) -> global_hotkey::hotkey::Code {
    global_hotkey::hotkey::Code::from_str(&self.to_string()).unwrap()
  }

  pub fn from_global_hotkeys(code: global_hotkey::hotkey::Code) -> Option<KeyCode> {
    code.to_string().parse().ok()
  }
}

#[napi(string_enum)]
pub enum Mods {
  Control,
  Alt,
  AltGraph,
  CapsLock,
  Fn,
  FnLock,
  Meta,
  NumLock,
  ScrollLock,
  Symbol,
  SymbolLock,
  Hyper,
  Shift,
  Super,
}

impl Mods {
  pub fn global_hotkeys(&self) -> Modifiers {
    match self {
      Mods::Control => Modifiers::CONTROL,
      Mods::Alt => Modifiers::ALT,
      Mods::Shift => Modifiers::SHIFT,
      Mods::Super => Modifiers::SUPER,
      Mods::AltGraph => Modifiers::ALT_GRAPH,
      Mods::CapsLock => Modifiers::CAPS_LOCK,
      Mods::Fn => Modifiers::FN,
      Mods::FnLock => Modifiers::FN_LOCK,
      Mods::Meta => Modifiers::META,
      Mods::NumLock => Modifiers::NUM_LOCK,
      Mods::ScrollLock => Modifiers::SCROLL_LOCK,
      Mods::Symbol => Modifiers::SYMBOL,
      Mods::SymbolLock => Modifiers::SYMBOL_LOCK,
      Mods::Hyper => Modifiers::HYPER,
    }
  }

  pub fn from_global_hotkeys(modifier: Modifiers) -> Option<Mods> {
    match modifier {
      Modifiers::CONTROL => Some(Mods::Control),
      Modifiers::ALT => Some(Mods::Alt),
      Modifiers::SHIFT => Some(Mods::Shift),
      Modifiers::SUPER => Some(Mods::Super),
      Modifiers::ALT_GRAPH => Some(Mods::AltGraph),
      Modifiers::CAPS_LOCK => Some(Mods::CapsLock),
      Modifiers::FN => Some(Mods::Fn),
      Modifiers::FN_LOCK => Some(Mods::FnLock),
      Modifiers::META => Some(Mods::Meta),
      Modifiers::NUM_LOCK => Some(Mods::NumLock),
      Modifiers::SCROLL_LOCK => Some(Mods::ScrollLock),
      Modifiers::SYMBOL => Some(Mods::Symbol),
      Modifiers::SYMBOL_LOCK => Some(Mods::SymbolLock),
      Modifiers::HYPER => Some(Mods::Hyper),
      _ => None,
    }
  }
}

#[napi]
#[derive(Clone)]
pub struct Desc {
  pub code: KeyCode,
  pub mods: Vec<Mods>,
}

impl Desc {
  pub fn new(code: KeyCode, mods: Vec<Mods>) -> Self {
    Self { code, mods }
  }
}

#[napi]
pub enum EventType {
  Pressed,
  Released,
}

#[napi]
pub struct Event {
  pub code: KeyCode,
  pub mods: Vec<Mods>,
  pub event_type: EventType,
}
